import re
import pandas as pd
 
 
# Define the zone extraction function
def extract_zones(address):
    if pd.isna(address):
        return {}
    # Define the zones and common variations/misspellings
    zones = {
        "Sector G/5-11": [
            "g-(5?\d|11)",
            "g - (5?\d|11)",
            "g (5?\d|11)",
            "g-(5?\d|11)/(5?\d|11)",
            "g (5?\d|11)/(5?\d|11)",
            "[g]-(5?\d|11)/(5?\d*|11)",
            "[g]/(5?\d*|11)",
            "[g]\\s*(5?\d|11)",
        ],
        "Sector G/12-20": [
            "g-(12?\d|20)",
            "g - (12?\d|20)",
            "g (12?\d|20)",
            "g-(12?\d|20)/(12?\d|20)",
            "g (12?\d|20)/(12?\d|20)",
            "[g]-(12?\d|20)/(12?\d*|20)",
            "[g]/(12?\d*|20)",
            "[g]\\s*(12?\d|20)",
        ],
        "Sector H/5-11": [
            "h-(5?\d|11)",
            "h - (5?\d|11)",
            "h (5?\d|11)",
            "h-(5?\d|11)/(5?\d|11)",
            "h (5?\d|11)/(5?\d|11)",
            "[h]-(5?\d|11)/(5?\d*|11)",
            "[h]/(5?\d*|11)",
            "[h]\\s*(5?\d|11)",
        ],
        "Sector H/12-20": [
            "h-(12?\d|20)",
            "h - (12?\d|20)",
            "h (12?\d|20)",
            "h-(12?\d|20)/(12?\d|20)",
            "h (12?\d|20)/(12?\d|20)",
            "[h]-(12?\d|20)/(12?\d*|20)",
            "[h]/(12?\d*|20)",
            "[h]\\s*(12?\d|20)",
        ],
        "Sector I/5-11": [
            "I-(5?\d|11)",
            "I - (5?\d|11)",
            "I (5?\d|11)",
            "I-(5?\d|11)/(5?\d|11)",
            "I (5?\d|11)/(5?\d|11)",
            "[i]-(5?\d|11)/(1?\d*|11)",
            "[i]/(5?\d*|11)",
            "[i]\\s*(5?\d|11)",
        ],
        "Sector I/12-20": [
            "i-(12?\d|20)",
            "i - (12?\d|20)",
            "i (12?\d|20)",
            "i-(12?\d|20)/(12?\d|20)",
            "i (12?\d|20)/(12?\d|20)",
            "[i]-(12?\d|20)/(12?\d*|20)",
            "[i]/(12?\d*|20)",
            "[i]\\s*(12?\d|20)",
        ],
        "Murree Road": [
            "iqbal camp",
            "rawal park",
            "thana waris khan",
            "dhok khabba",
            "tipu road",
            "sir syed chowk",
            "jan colony",
            "kohistan colony",
            "dhok farman ali",
            "iqbal town",
            "mohammadi colony",
            "circular road",
            "raja town",
            "muhallah faisalabad",
            "qasim abad",
            "murshad town",
            "rawalpindi medical university",
            "rawalpindi institute of cardiology - ric",
            "sultan ka khuh",
            "chandni chowk",
            "glass factory",
            "benazir hospital",
            "tamasip abad",
            "ali nawaz chowk",
            "waris khan",
            "officer's colony",
            "al-muslim masjid",
            "marir hassan",
            "rahim town",
            "col yousuf colony",
            "haider camp",
            "shamsabad",
            "6th road",
            "amar pura",
            "mukha singh state",
            "dhok chirag din",
            "arya mohalla",
            "millat colony",
            "akbar market",
            "awan town",
        ],
        "Sector E/5-11": [
            "e-(5?\d|11)",
            "e - (5?\d|11)",
            "e (5?\d|11)",
            "e-(5?\d|11)/(5?\d|11)",
            "e (5?\d|11)/(5?\d|11)",
            "[e]-(5?\d|11)/(5?\d*|11)",
            "[e]/(5?\d*|11)",
            "[e]\\s*(5?\d|11)",
        ],
        "Sector E/12-20": [
            "e-(12?\d|20)",
            "e - (12?\d|20)",
            "e (12?\d|20)",
            "e-(12?\d|20)/(12?\d|20)",
            "e (12?\d|20)/(12?\d|20)",
            "[e]-(12?\d|20)/(12?\d*|20)",
            "[e]/(12?\d*|20)",
            "[e]\\s*(12?\d|20)",
        ],
        "Sector F/5-11": [
            "f-(5?\d|11)",
            "f - (5?\d|11)",
            "f (5?\d|11)",
            "f-(5?\d|11)/(5?\d|11)",
            "f (5?\d|11)/(5?\d|11)",
            "[f]-(5?\d|11)/(5?\d*|11)",
            "[f]/(5?\d*|11)",
            "[f]\\s*(5?\d|11)",
        ],
        "Sector F/12-20": [
            "f-(12?\d|20)",
            "f - (12?\d|20)",
            "f (12?\d|20)",
            "f-(12?\d|20)/(12?\d|20)",
            "f (12?\d|20)/(12?\d|20)",
            "[f]-(12?\d|20)/(12?\d*|20)",
            "[f]/(12?\d*|20)",
            "[f]\\s*(12?\d|20)",
        ],
        "DHA/Bahria": [
            "dha",
            "bahria",
            "zaraj",
            "humak",
            "bahriatown",
            "pwd",
            "bahria town",
            "defence housing society",
        ],
        "Heavy - ISB": ["heavy - isb", "heavy industrial area"],
        "Chaklala": [
            "chaklala",
            "Topi Rakh Auditorium",
            "Askari 6",
            "Ayub Colony",
            "Bostan Khan Road",
            "Afzal Town",
            "Askari 1",
            "Askari 3",
            "Champion Colony",
            "Commercial Market",
            "Askari 10",
            "Railway Scheme 9",
            "Askari 8",
            "Railway Scheme 1 To 4",
            "Park Road",
            "Faisal Colony",
            "Wallayat Homes",
            "Shah Khalid Colony",
            "Gulzar-e-Quaid",
            "Airport Villas",
            "Gracey Lane",
            "Gulistan Colony",
            "Wavel Lines",
            "Ghareeb Abad",
            "Rahim Abad",
            "Rose Lane",
            "Scheme 1",
            "Scheme 2",
            "Katchehri Chowk",
            "Scheme 3",
            "Eastridge Colony",
            "Jhanda Chichi",
            "Nasir Colony",
            "Askari 9",
            "Ideal Homes",
            "Noor E Ilahi Colony",
            "Execuitive Villas",
            "Police Line",
            "Banaras Colony",
            "Airport Chowk",
            "Askari 13",
            "Dhok Kashmirian",
            "AECHS",
            "Askari 4",
            "National Colony",
            "Dhok Hafiz",
            "Burma Shell",
            "Judicial Colony",
            "Nazir Abad",
            "Khayaban E Tanvir",
            "Fazal Town Phase 1 - 2",
            "Gulzar E Quaid Extension",
            "Muree Brewrey Office",
            "Shah Faisal Colony",
            "Jaan Colony",
            "Service Road West",
            "New Gulzar E Quaid",
            "TCS Stop",
            "Askari 5",
            "Azeem Town",
            "Wallayat Colony",
            "Palm City",
            "Ayub Park",
            "Daad Khan Colony",
            "Noorani Muhalla",
            "Nawaz Colony 1 - 2",
            "Khayaban E Sarfraz",
            "Civil Line",
            "High Court Road",
            "Dhok Chodhrian",
            "New Afzal Town",
            "Askari 2",
            "Askari 12",
            "Mohalla Ghousia",
            "Chaklala Village",
            "Qadeer Market",
            "Dhok Kamal Din",
            "Ghauri Town - Phase 4",
            "Ghauri Town - Phase 3",
            "Marwa Town",
            "Sanam Chowk",
            "Shareef Abad",
            "Ghouri Garden",
            "Kalma Chowk",
            "Ghauri Town - Phase 7",
            "Dhoke Gangal",
            "Madina Town",
            "Ghauri Town - Phase 2",
            "Koral Chowk",
            "Ghauri Town - Phase 1",
            "Ghauri Town - Phase 5",
            "Sarfraz Town",
            "Gulshan-E-Tarlai",
            "Gulberg Town",
            "Talai Kalan",
            "Sher Ali Town",
            "Taramri",
            "Irfanabad Town",
            "Jagiot Road",
            "Mehrban Town",
            "Ghazi Shah Imam Road",
        ],
        "Adyala Road": [
            "hassan home",
            "adiyala road",
            "munawar colony",
            "gulshan abad",
            "ali town",
            "tulsa road",
            "fort road",
            "pir meher ali shah town",
            "aghosh housing society",
            "army colony",
            "khawaja cooperation",
            "rabia bungalows",
            "sher zaman colony",
            "wahdat colony",
            "gulshan shumal",
            "banker's colony",
            "khalid colony phase 2",
            "zulfikar colony",
            "al-haram city",
            "khyaban e suleman",
            "lalazar estate",
            "radio colony",
            "dhoke imam din",
            "mehmood abad",
            "safari enclave",
            "sinjoli state",
            "ghorak pur",
            "askari 7",
            "gulshan e jalil",
            "raja akram colony",
            "kehkeshan colony",
            "national colony 1 - 2",
            "dhok noor",
            "arl colony",
            "garden villa",
            "dhok juma",
            "caltex road",
            "kotha kalan",
            "bank colony",
            "gulbahar colony",
            "khayaban e jinah",
            "doctor colony",
            "nadir street",
            "hassan street",
            "sharoon colony",
            "green villa",
            "janjua town",
            "karli village",
            "habib lane",
            "dhok rajgan",
            "punjab housing society",
            "hill view lane",
            "kalyal village",
            "sapphire villas",
            "morgah",
            "dhok pharian",
            "new lalazar",
            "saliha street",
            "mubarik lane",
            "baqir colony",
            "defence road",
            "maryam green city",
            "askari 14",
            "shahpur",
            "chakri",
            "clifton town",
            "old lalazar",
            "fazli street",
            "gadgal village",
            "adiyala jail",
            "sarmarzar",
            "zafar akbar road",
        ],
        "Peshawar Road": [
            "range road",
            "haji camp",
            "cobb line",
            "golra mor",
            "qabristan chowk",
            "dhok gujran",
            "mukrram town",
            "new chakra",
            "shabbir lane east",
            "peshawar road lane 7",
            "shalley valley",
            "awan town",
            "peshawar road lane 6",
            "peshawar road lane 4",
            "pasban flats",
            "transit camp",
            "sco unit 62",
            "charing cross",
            "ashayana chowk",
            "race course road",
            "peshawar road lane 5",
            "peshawar road lane 2",
            "nagi road",
            "gulshan e khudadad 1 to 5",
            "bhata chowk",
            "gulshan e nayab",
            "faisal colony",
            "peshawar road lane 3",
            "niazi town",
            "cantt view colony",
            "shabbir lane west",
            "naseer abad",
            "quaid e azam international hospital",
            "muslim abad",
            "pirwadhai mor",
            "bilal umer shaheed colony",
            "millat abad",
            "old chakra",
            "officer's colony",
            "dhok mustaqim",
            "dhok banaras",
            "afshan colony",
            "friend's colony",
            "javed sultan shaheed colony",
            "dhok chodhrian",
            "madina town",
            "kainat adda",
            "aliabad",
            "bait e sada colony",
            "postal colony",
            "qasai chowk",
            "krl flats",
            "blue land officer coloney",
            "jhangi syedian",
            "green land officer coloney",
            "qasim market",
            "pia colony",
            "chour chowk",
            "koh e noor mil",
            "ptcl colony",
            "qasimabad",
            "misrial road",
            "ilyas colony",
            "ogdcl society",
            "meherabad",
            "gulistan e fatima",
            "najam shaheed road",
            "peshawar road lane 1",
            "parade lane",
            "muhammadi town",
            "bakery chowk",
            "raja akram road",
            "allahabad",
            "mohalla qureshian",
            "26 # chungi",
            "shimla valley",
            "cmt golra",
        ],
        "Banigala": [
            "hill view road",
            "imran khan road",
            "pakistan colony",
            "green valley society islamabad",
            "qasim avenue",
            "hussain road",
            "akram road",
            "muzaffar khan road",
            "ghaus al azam road",
            "river side enclave",
            "dr. aq khan school road",
            "imran khan chowk",
            "raja ashraf road",
            "abbasi road street 14-b",
            "lake view lanes colony",
            "korang road",
            "north banni galla",
            "lakhwal",
            "khyber city town",
            "Kiani Road",
            "Madina Town",
            "PTV Colony",
            "Kot Hathyal",
            "Jillani Town",
            "Colonel Aman Ullah Road",
            "Nai Abadi",
            "Sehri Chowk",
            "Margallah Valley",
            "Mungo Town",
            "Ahmad Town",
            "17 Mile",
            "Mohalla Syadan",
            "University Town",
            "Muslim Town",
            "Belgium Town",
            "Ameen Abbasi Town",
            "Dhoke Mohri",
            "Company Road",
            "Ali Town Kundi",
            "Prince Road",
            "Usman Abad",
            "Abdullah Town",
            "Shahpur",
            "Azmat Town",
            "Green Avenue - Phase 1",
            "Park View",
            "Kurri Road",
            "Green Avenue - Phase 2",
            "Hostel City",
            "New Chatta Bakhtawar",
            "Mohra Noor",
            "Junaid Mughal Town",
            "Park Enclave",
            "Chatta Road",
            "Chak Shehzad Farms",
            "Gulshan - E - Alhuda",
            "Shahzad Town",
            "COMSATS University",
            "Jinnah Complex",
            "NIH Hospital",
        ],
        "Wah Cantt": [
            "d-12",
            "d - 12",
            "d/12",
            "d-12/(1?\d|20)",
            "d - 12/(1?\d|20)",
            "b-17",
            "d - 17",
            "b/17",
            "b-17/(1?\d|20)",
            "b - 17/(1?\d|20)",
            "Wah Cantt",
            "Wah",
        ],
        "Naval Anchorage": ["Naval Anchorage", "anchorage"],
    }
 
    # Create a regex pattern to match any of the zone variations
    patterns = {
        zone: [
            re.compile(r"\b{}\b".format(variation), re.IGNORECASE)
            for variation in variations
        ]
        for zone, variations in zones.items()
    }
 
    # Find all matching zones and terms in the address
    matched_zones = {}
    for zone in zones:
        matched_terms = []
        for pattern in patterns[zone]:
            if pattern.search(address):
                matched_terms.append(pattern.pattern)
        if matched_terms:
            matched_zones[zone] = matched_terms
 
    return matched_zones
 
 
# Read data from CSV
data = pd.read_csv("June_Islamabad_Wah_Data_2024_07_30 (1).csv")
 
data = data.drop(columns=["pickup_address", "origin_city_name", "dest_city_name", "weight"])
 
# drop data columns
data = data.dropna()
 
data["delivery_address"] = data["delivery_address"].fillna("").astype(str)
 
# Initialize columns to 0
for zone in data.columns[
    1:-1
]:  # Skipping 'Islamabad' and 'Count of Zones matched' columns
    data[zone] = 0
 
# Apply the zone extraction function to each address in the 'delivery_address' column
data["Matched Zones"] = data["delivery_address"].apply(lambda x: extract_zones(x))
 
# Update the DataFrame with 1 for matched zones and save matched terms
data["Matched Terms"] = ""
 
for i, row in data.iterrows():
    matched_zones = row["Matched Zones"]
    matched_terms_list = []
    for zone, terms in matched_zones.items():
        data.at[i, zone] = 1
        matched_terms_list.extend(terms)
    data.at[i, "Count of Zones matched"] = len(matched_zones)
    data.at[i, "Matched Terms"] = ", ".join(matched_terms_list)
 
# Drop the 'Matched Zones' column as it's no longer needed
data.drop(columns=["Matched Zones"], inplace=True)
 
# Save the updated DataFrame to a new CSV file
data.to_csv("June (Detailed).csv", index=False)
 
print("Updated file saved successfully.")